In [2]:
import numpy as np

In [3]:
x = np.arange(16)

In [4]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [5]:
x[3]

3

In [6]:
x[3:9]

array([3, 4, 5, 6, 7, 8])

In [7]:
x[3:9:2]

array([3, 5, 7])

In [8]:
[x[3],x[5],x[8]]

[3, 5, 8]

In [9]:
ind = [3 ,5 ,8]

In [10]:
x[ind]

array([3, 5, 8])

In [11]:
ind = np.array([[0,2],
                [1,3]])

In [12]:
x[ind]

array([[0, 2],
       [1, 3]])

In [15]:
X = x.reshape(4 ,-1)

In [17]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [18]:
row = np.array([0,1,2])
col = np.array([1,2,3])
X[row,col] #取（0，1） （1，2） （2，3）

array([ 1,  6, 11])

In [20]:
X[0,col]

array([1, 2, 3])

In [21]:
X[:2, col]

array([[1, 2, 3],
       [5, 6, 7]])

In [22]:
col = [True, False, True, True]
X[1:3,col]

array([[ 4,  6,  7],
       [ 8, 10, 11]])

## numpy.array 比较

In [23]:
x = np.arange(16)

In [24]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [27]:
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [28]:
x>3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [29]:
x <= 3

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [30]:
x == 3

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [31]:
x != 3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [33]:
2 * x == 24 - 4 * x #解方程

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [34]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [39]:
Y = X<6
Y

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [43]:
Y[0]

array([ True,  True,  True,  True])

In [44]:
Y[0,0:3]

array([ True,  True,  True])

In [48]:
X[Y]

array([0, 1, 2, 3, 4, 5])

In [50]:
row = Y[0:2]
col = Y[0,4]
row

IndexError: index 4 is out of bounds for axis 1 with size 4

In [51]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [52]:
x <= 3

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [53]:
np.sum(x <= 3)

4

In [54]:
np.count_nonzero(x <= 3)

4

In [55]:
np.any( x == 0)

True

In [56]:
np.any(x < 0)

False

In [57]:
np.all(x>0)

False

In [58]:
np.all(x>=0)

True

In [59]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [63]:
np.sum(X % 2 == 0)

8

In [62]:
np.sum(X % 2 == 0, axis = 1)

array([2, 2, 2, 2])

In [64]:
np.sum(X % 2 == 0,axis = 0)

array([4, 0, 4, 0])

In [70]:
np.sum((x > 3) & (x < 10))

6

In [71]:
(x>3) & (x<10)

array([False, False, False, False,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False])

In [72]:
np.sum((x % 2==0) | (x > 10))

11

In [75]:
np.sum(~(x==0)) #非

15

In [76]:
X[X<5]

array([0, 1, 2, 3, 4])

In [77]:
x[x<5]

array([0, 1, 2, 3, 4])

In [78]:
X[X[:,3] % 3 == 0, :]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])