# numpy.array 中的运算

In [1]:
import numpy as np

In [5]:
n = 1000000
L = [i for i in range (n)]
L

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [3]:
A = []

In [4]:
for e in L:
    A.append(2 * e)
A

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [7]:
%time
A = []
for e in L:
    A.append(2 * e)

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 4.05 µs


In [8]:
%time
A = [2 * e for e in L]

CPU times: user 1e+03 ns, sys: 0 ns, total: 1e+03 ns
Wall time: 3.1 µs


In [9]:
L = np.arange(n)

In [17]:
%%timeit
A = np.array(2 * e for e in L)

1.39 µs ± 13.7 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [19]:
%%timeit
A = 2 * L

300 µs ± 3.1 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [20]:
A

array(<generator object <genexpr> at 0x7fbdd85a6190>, dtype=object)

In [21]:
n  = 10
L = np.arange(n)
2 * L

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Universal Functions

In [24]:
X = np.arange(1,16).reshape((3,-1))

In [25]:
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [26]:
X+1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [27]:
X-1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [28]:
X * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [29]:
X / 2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [30]:
X // 2

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]])

In [31]:
X ** 2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]])

In [32]:
X % 2

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]])

In [33]:
1/ X

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [34]:
np.abs()

TypeError: absolute() takes from 1 to 2 positional arguments but 0 were given

In [35]:
np.abs(X)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [36]:
np.sin(X)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [37]:
np.cos(X)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153],
       [ 0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791]])

In [38]:
np.tan(X)

array([[ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
         1.15782128e+00, -3.38051501e+00],
       [-2.91006191e-01,  8.71447983e-01, -6.79971146e+00,
        -4.52315659e-01,  6.48360827e-01],
       [-2.25950846e+02, -6.35859929e-01,  4.63021133e-01,
         7.24460662e+00, -8.55993401e-01]])

In [39]:
np.exp(X)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06]])

In [40]:
np.power(3, X)

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]])

In [42]:
np.log(X) #ln

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [43]:
np.log2(X)

array([[0.        , 1.        , 1.5849625 , 2.        , 2.32192809],
       [2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809],
       [3.45943162, 3.5849625 , 3.70043972, 3.80735492, 3.9068906 ]])

In [44]:
np.log10(X)

array([[0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ],
       [0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ],
       [1.04139269, 1.07918125, 1.11394335, 1.14612804, 1.17609126]])

## 矩阵运算

In [45]:
A = np.arange(4).reshape(2,-1)

In [46]:
A

array([[0, 1],
       [2, 3]])

In [47]:
B = np.full((2,2), 10)

In [48]:
B

array([[10, 10],
       [10, 10]])

In [49]:
A + B

array([[10, 11],
       [12, 13]])

In [51]:
A * B #不是矩阵相乘 而是对应位置相乘

array([[ 0, 10],
       [20, 30]])

In [53]:
A / B #同上

array([[0. , 0.1],
       [0.2, 0.3]])

In [54]:
A.dot(B) #矩阵乘法

array([[10, 10],
       [50, 50]])

In [56]:
A.T #转置

array([[0, 2],
       [1, 3]])

In [62]:
C = np.full((3,3) , 666)

In [63]:
C

array([[666, 666, 666],
       [666, 666, 666],
       [666, 666, 666]])

In [59]:
A.dot(c)

NameError: name 'c' is not defined

In [64]:
A.dot(C)

ValueError: shapes (2,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

## 向量和矩阵运算

In [68]:
v = np.array([1,2])
v

array([1, 2])

In [66]:
A

array([[0, 1],
       [2, 3]])

In [67]:
v + A #向量和每一行做加法 what's this?

array([[1, 3],
       [3, 5]])

In [74]:
A.shape[0]

2

In [71]:
v

array([1, 2])

In [72]:
np.vstack([v,v])

array([[1, 2],
       [1, 2]])

In [78]:
test = np.arange(6).reshape(2,-1)
test

array([[0, 1, 2],
       [3, 4, 5]])

In [80]:
test.shape[0]

2

In [81]:
test.shape[1]

3

In [82]:
np.vstack([v]* A.shape[0])

array([[1, 2],
       [1, 2]])

In [83]:
np.vstack([v]* A.shape[0]) + A

array([[1, 3],
       [3, 5]])

In [86]:
np.tile(v,(2,1)) #把v在行向量上堆叠2次 列上堆叠1次

array([[1, 2],
       [1, 2]])

In [87]:
np.tile(v,(2,1)) + A

array([[1, 3],
       [3, 5]])

In [89]:
v + A# 更自然 但是无厘头

array([[1, 3],
       [3, 5]])

In [90]:
v

array([1, 2])

In [91]:
A

array([[0, 1],
       [2, 3]])

In [93]:
v * A #无意义

array([[0, 2],
       [2, 6]])

In [94]:
np.dot(v,A)

array([4, 7])

In [95]:
v.dot(A)

array([4, 7])

In [98]:
A.dot(v) #向量和矩阵乘法 numpy会自动判断是行向量还是列向量 在这里是当列向量使用的

array([2, 8])

## 矩阵的逆

In [99]:
A

array([[0, 1],
       [2, 3]])

In [100]:
np.linalg.inv(A) #numpy.LinearAlgebra.inverse

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [101]:
invA = np.linalg.inv(A)

In [102]:
invA

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [103]:
invA * A

array([[-0. ,  0.5],
       [ 2. ,  0. ]])

In [104]:
np.dot(invA,A)

array([[1., 0.],
       [0., 1.]])

In [105]:
X = np.arange(16).reshape(2,-1)

In [106]:
X

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [107]:
np.linalg.inv(X)

LinAlgError: Last 2 dimensions of the array must be square

In [115]:
pinvX = np.linalg.pinv(X) # Pseudo - 伪逆矩阵

In [116]:
X.dot(pinvX)

array([[ 1.00000000e+00, -1.94289029e-16],
       [ 6.66133815e-16,  1.00000000e+00]])