In [2]:
import numpy as np
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
X = np.arange(15).reshape((3,5))
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## 基本属性

In [120]:
x.ndim
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
X.ndim

2

In [7]:
x.shape

(10,)

In [8]:
x.shape

(10,)

In [9]:
X.shape

(3, 5)

In [10]:
x.size


10

In [124]:
x.shape[0]

10

In [122]:
x.shape

(10,)

In [121]:
X.size

15

## numpy.array 数据访问

In [12]:
x[0]

0

In [13]:
x[-1]

9

In [14]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
X[0][0] #不建议这么写

0

In [17]:
X[(0,0)]

0

In [18]:
X[0,0]

0

In [19]:
x[2,2]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [20]:
X[2,2]

12

In [21]:
x[0:5] #[0,5)

array([0, 1, 2, 3, 4])

In [22]:
x[:5]

array([0, 1, 2, 3, 4])

In [23]:
x[5:]

array([5, 6, 7, 8, 9])

In [24]:
x[::]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
x[::2]

array([0, 2, 4, 6, 8])

In [26]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [27]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [29]:
X[:2,:3] #前两行 前三列

array([[0, 1, 2],
       [5, 6, 7]])

In [30]:
X[:2][:3] #result is wrong

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [31]:
X[:2, ::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [32]:
X[::-1,::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [33]:
X[0]

array([0, 1, 2, 3, 4])

In [34]:
X[0,:]

array([0, 1, 2, 3, 4])

In [36]:
X[0,:].ndim

1

In [37]:
X[:, 0]

array([ 0,  5, 10])

In [38]:
subX = X[:2, :3]

In [39]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [43]:
subX[0,0] = 100
subX #subX指向原矩阵的一部分 一改全改

array([[100,   1,   2],
       [  5,   6,   7]])

In [41]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [44]:
X[0,0] = 0
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [45]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [46]:
#bu xiang guan

In [47]:
subX = X[:2, :3].copy() #这样就没关系了

In [48]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [49]:
subX[0,0] = 100

In [50]:
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [51]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## Reshape

In [52]:
x.shape

(10,)

In [53]:
x.ndim

1

In [54]:
x.reshape(2,5) #不改原来的数值

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [55]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
y = x.reshape(2,5)

In [57]:
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [58]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
A = x.reshape(2,5)

In [60]:
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [61]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
x.shape

(10,)

In [63]:
B = x.reshape(1,10)

In [64]:
B.shape

(1, 10)

In [65]:
B #x是数组 B是一维向量

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [66]:
x.reshape(10, -1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [67]:
x.reshape(10 ,-1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [68]:
x.reshape(-1 , 10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [69]:
x.reshape(2 ,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [70]:
x.reshape(3, -1)

ValueError: cannot reshape array of size 10 into shape (3,newaxis)

## 合并操作

In [71]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [72]:
x
y

array([3, 2, 1])

In [73]:
y

array([3, 2, 1])

In [74]:
x

array([1, 2, 3])

In [75]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [81]:
z = np.array([666,666,666])
z

array([666, 666, 666])

In [82]:
np.concatenate([x,y,z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [84]:
A = np.array([[1,2,3],
              [4,5,6]])

In [86]:
np.concatenate([A,A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [87]:
np.concatenate( [A, A] , axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [90]:
np.concatenate([A,z] ) #concatenate 只能处理维度相同的

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [92]:
np.concatenate([A, z.reshape(1,3)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [93]:
A2 = np.concatenate([A, z.reshape(1,3)])

In [94]:
A2

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [95]:
np.vstack([A,z]) #容错性更高

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [96]:
B = np.full((2,2) , 100)

In [97]:
B

array([[100, 100],
       [100, 100]])

In [100]:
np.hstack([A,B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

## 分割操作

In [102]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
x1, x2, x3 = np.split( x, [3,7] )

In [104]:
x1 #3不包含

array([0, 1, 2])

In [105]:
x2

array([3, 4, 5, 6])

In [106]:
x3

array([7, 8, 9])

In [107]:
np.split(x, [5])

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [108]:
A = np.arange(16).reshape((4,4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [115]:
A1, A2 = np.split(A,[2], axis = 1) #默认行维度分割 0为行 1为列

In [116]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [117]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [118]:
np.vsplit(A,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [119]:
np.hsplit(A,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]