In [1]:
import numpy

In [2]:
numpy.__version__

'1.21.5'

In [4]:
import numpy as np

In [5]:
np.__version__

'1.21.5'

## python list feature


In [6]:
L = [i for i in range(10)]

In [13]:
L[5] = "machine learning"

In [12]:
L

[0, 1, 2, 3, 4, 'machine learning', 6, 7, 8, 9]

In [14]:
import array
arr = array.array('i',[i for i in range (10)])
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr[5]

5

In [16]:
arr[5] = "machine learning"

TypeError: an integer is required (got type str)

numpy.array

In [20]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
nparr.dtype

dtype('int64')

In [24]:
nparr[5] = 5.0
nparr.dtype

dtype('int64')

## 浮点数自动回截位 隐式转换

In [27]:
nparr2 = np.array([1,2,3.0])
nparr2

array([1., 2., 3.])

In [29]:
nparr2.dtype

dtype('float64')

## 其他创建numpy.array的方法

In [31]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
np.zeros(10).dtype

dtype('float64')

In [35]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [40]:
np.zeros(shape = (3,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [42]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [44]:
np.ones(shape=(3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [48]:
np.full(shape=(3,5) ,fill_value=666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

## arange

In [50]:
[i for i in range (0, 20, 2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [53]:
np.arange(0,20,0.2) #可以传入浮点数步长

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4, 10.6, 10.8,
       11. , 11.2, 11.4, 11.6, 11.8, 12. , 12.2, 12.4, 12.6, 12.8, 13. ,
       13.2, 13.4, 13.6, 13.8, 14. , 14.2, 14.4, 14.6, 14.8, 15. , 15.2,
       15.4, 15.6, 15.8, 16. , 16.2, 16.4, 16.6, 16.8, 17. , 17.2, 17.4,
       17.6, 17.8, 18. , 18.2, 18.4, 18.6, 18.8, 19. , 19.2, 19.4, 19.6,
       19.8])

## linspace

In [56]:
np.linspace(0,20,10) #0到20（左闭右闭）区间里等长截出10个点

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

## random

In [57]:
np.random.randint(0,10)

7

In [59]:
np.random.randint(0,20,10) #在0到20的区域里(左闭右开)生成一个10维向量

array([ 2, 19, 15,  9, 16, 10,  8,  7, 19,  8])

In [60]:
np.random.randint(4,8,size = 10)

array([6, 4, 6, 4, 6, 4, 4, 6, 7, 5])

In [61]:
np.random.randint(4,8,size = (3,5))

array([[7, 7, 6, 6, 4],
       [7, 5, 5, 6, 6],
       [6, 5, 6, 5, 5]])

In [62]:
np.random.seed(666)
np.random.randint(4,8,size = (3,5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [63]:
np.random.seed(666)
np.random.randint(4,8,size = (3,5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [64]:
np.random.rand()

0.2811684913927954

In [65]:
np.random.rand()

0.4628416859214477

In [67]:
np.random.random(10)

array([0.76706421, 0.81995656, 0.39747625, 0.31644109, 0.15551206,
       0.73460987, 0.73159555, 0.8578588 , 0.76741234, 0.95323137])

In [68]:
np.random.random((3,5))

array([[0.29097383, 0.84778197, 0.3497619 , 0.92389692, 0.29489453],
       [0.52438061, 0.94253896, 0.07473949, 0.27646251, 0.4675855 ],
       [0.31581532, 0.39016259, 0.26832981, 0.75366384, 0.66673747]])

In [73]:
np.random.normal(10,100,(3,5)) #均值为10 方差为100 size为（3，5）

array([[  21.21217026,   13.18538839,   -9.20628514,   88.6112843 ,
        -159.04631421],
       [ -88.87390714,   41.39856302,   49.63856739,   67.65658375,
           2.98059308],
       [ 101.25043617,  110.4704966 ,   51.85992895, -142.90245423,
         102.48753198]])

In [74]:
np.random.normal?

In [75]:
np.random?

In [77]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of numpy.random.mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    .. note::
        New code should use the ``normal`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution