## 聚合操作

In [1]:
import numpy as np

In [3]:
L = np.random.random(100)

In [5]:
L

array([0.29783893, 0.72481435, 0.72617028, 0.90971537, 0.06566393,
       0.49153011, 0.59126772, 0.14262162, 0.15853989, 0.89566647,
       0.09915374, 0.03383242, 0.97931961, 0.27348622, 0.73047615,
       0.89672245, 0.57123459, 0.40000972, 0.42800546, 0.68462924,
       0.51982741, 0.31414298, 0.47678131, 0.61735329, 0.48124841,
       0.3667412 , 0.76580432, 0.18144265, 0.18892956, 0.91169323,
       0.74420554, 0.49839921, 0.50476619, 0.807673  , 0.58307674,
       0.91133123, 0.82183469, 0.13031944, 0.7315254 , 0.31207187,
       0.28801017, 0.3042799 , 0.22092484, 0.32242569, 0.54267177,
       0.9702128 , 0.0531774 , 0.43301996, 0.06200848, 0.14003512,
       0.08648491, 0.84523208, 0.44751364, 0.47345997, 0.37873938,
       0.17985874, 0.26357477, 0.78262459, 0.95752546, 0.17506733,
       0.89412331, 0.9441827 , 0.03062322, 0.69205952, 0.76324859,
       0.13412458, 0.13877133, 0.45920649, 0.0838183 , 0.99284288,
       0.49934516, 0.29300347, 0.16827912, 0.99322039, 0.47453

In [6]:
sum(L)

50.6463106731055

In [10]:
np.sum(L) # difference? numpy much more efficient!

50.646310673105475

In [11]:
np.min(L)

0.030623218066681113

In [12]:
np.max(L)

0.9932203879991677

In [14]:
L.max()

0.9932203879991677

In [15]:
X = np.arange(16).reshape(4, -1)

In [16]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [17]:
np.sum(X)

120

In [24]:
def SumAll (n):
    sum = 0
    for i in range(n+1):
        sum += i
    return sum
x = SumAll(15)

In [25]:
x

120

In [26]:
np.sum(X, axis = 0) #加到剩下一行

array([24, 28, 32, 36])

In [27]:
np.sum(X,axis = 1)

array([ 6, 22, 38, 54])

In [28]:
np.prod(X) #所有元素乘积

0

In [29]:
np.prod(X +1)

20922789888000

In [30]:
np.mean(X) #求平均值

7.5

In [32]:
np.median(X) #求中位数

7.5

In [33]:
v = np.array([1,1,2,2,10])
np.mean(v)

3.2

In [35]:
np.median(v)

2.0

In [39]:
np.percentile(v,q = 50) #百分之q的人比它小

2.0

In [40]:
np.percentile(v,q = 100)

10.0

In [41]:
for percent in [0,25,50,75,100]:
    print(np.percentile(v,q = percent))

1.0
1.0
2.0
2.0
10.0


In [43]:
np.var(X) #方差

21.25

In [45]:
np.std(X) #标准差

4.6097722286464435

In [46]:
x = np.random.normal(0 ,1 ,1000000) #正态分布

In [47]:
x

array([ 1.22566834, -0.641659  ,  1.11629634, ...,  1.28253379,
        1.40044857, -0.04299538])

In [48]:
np.median(x)

-0.0013148303614787921

In [49]:
np.std(x)

1.0006533614878936

## 索引

In [50]:
np.min(x)

-5.317041467202772

In [52]:
np.argmin(x) #返回最小值的位置

444211

In [53]:
np.argmax(x)

631548

In [54]:
x[631548]

4.894450407985163

In [55]:
np.max(x)

4.894450407985163

## 排序和使用索引

In [56]:
x = np.arange(16)

In [57]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [58]:
np.random.shuffle(x) #乱序

In [59]:
x

array([ 4,  1, 15,  8,  9,  5,  7,  3,  0, 13, 14,  6,  2, 11, 10, 12])

In [60]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [61]:
x.sort()

In [62]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [63]:
X = np.random.randint(10, size = (4,4))

In [64]:
X

array([[8, 7, 4, 1],
       [9, 4, 2, 9],
       [5, 2, 3, 7],
       [5, 6, 6, 6]])

In [66]:
np.sort(X) #每一行排序

array([[1, 4, 7, 8],
       [2, 4, 9, 9],
       [2, 3, 5, 7],
       [5, 6, 6, 6]])

In [70]:
np.sort(X, axis = 1) #依照列排序,最后行有序 axis有异议的有sort，sum

array([[1, 4, 7, 8],
       [2, 4, 9, 9],
       [2, 3, 5, 7],
       [5, 6, 6, 6]])

In [69]:
np.sort(X , axis = 0)

array([[5, 2, 2, 1],
       [5, 4, 3, 6],
       [8, 6, 4, 7],
       [9, 7, 6, 9]])

In [71]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [72]:
np.random.shuffle(x)

In [73]:
x

array([12, 14,  3,  0, 15,  5,  7,  4, 13,  1, 10,  2,  8, 11,  6,  9])

In [74]:
np.argsort(x) #索引有序排列元素

array([ 3,  9, 11,  2,  7,  5, 14,  6, 12, 15, 10, 13,  0,  8,  1,  4])

In [76]:
x.argsort()

array([ 3,  9, 11,  2,  7,  5, 14,  6, 12, 15, 10, 13,  0,  8,  1,  4])

In [77]:
x

array([12, 14,  3,  0, 15,  5,  7,  4, 13,  1, 10,  2,  8, 11,  6,  9])

In [84]:
np.partition(x, 15) #快速排序第一步 找到标定点 然后把小放前 大放后 这个过程叫做partition

array([ 1,  4,  3,  0,  6,  5,  7,  8,  2,  9, 11, 10, 12, 13, 14, 15])

In [86]:
np.argpartition(x , 3) #不是以索引 而是结果为索引

array([ 3,  9, 11,  2,  7,  5,  6, 12, 14, 15, 10,  8,  1, 13,  4,  0])

In [87]:
X

array([[8, 7, 4, 1],
       [9, 4, 2, 9],
       [5, 2, 3, 7],
       [5, 6, 6, 6]])

In [89]:
np.argsort(X, axis = 1)

array([[3, 2, 1, 0],
       [2, 1, 0, 3],
       [1, 2, 0, 3],
       [0, 1, 2, 3]])